// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS39yHdC4Z1GIGE9mG02rZt2IlwcK4N-0',
    appId: '1:138345184351:web:35c906dc678b51b2d4efea',
    messagingSenderId: '138345184351',
    projectId: 'geminiapp-835d7',
    authDomain: 'geminiapp-835d7.firebaseapp.com',
    storageBucket: 'geminiapp-835d7.appspot.com',
    measurementId: 'G-FBR4SMWZTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ZsNEv5c_1wVzHtwrElybI6aBR0Kere8',
    appId: '1:138345184351:android:df8227af7904007bd4efea',
    messagingSenderId: '138345184351',
    projectId: 'geminiapp-835d7',
    storageBucket: 'geminiapp-835d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJWgoy3GNSvZ4CqmZtTxgz8FrGI5-DGs',
    appId: '1:138345184351:ios:0804da4c3442c863d4efea',
    messagingSenderId: '138345184351',
    projectId: 'geminiapp-835d7',
    storageBucket: 'geminiapp-835d7.appspot.com',
    iosBundleId: 'com.example.geminiAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJWgoy3GNSvZ4CqmZtTxgz8FrGI5-DGs',
    appId: '1:138345184351:ios:0804da4c3442c863d4efea',
    messagingSenderId: '138345184351',
    projectId: 'geminiapp-835d7',
    storageBucket: 'geminiapp-835d7.appspot.com',
    iosBundleId: 'com.example.geminiAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS39yHdC4Z1GIGE9mG02rZt2IlwcK4N-0',
    appId: '1:138345184351:web:363bded080705734d4efea',
    messagingSenderId: '138345184351',
    projectId: 'geminiapp-835d7',
    authDomain: 'geminiapp-835d7.firebaseapp.com',
    storageBucket: 'geminiapp-835d7.appspot.com',
    measurementId: 'G-E8PM2QR8HK',
  );
}
